import json
import sys
from pathlib import Path

# Allow running as a script from the project root
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.config import EVAL_RESULTS_PATH, DATA_DIR

EVAL_REPORT_PATH = DATA_DIR / "eval_report.md"

def generate_report(results_path: Path = EVAL_RESULTS_PATH, report_path: Path = EVAL_REPORT_PATH):
    """Read eval_results.json and write eval_report.md."""
    if not results_path.exists():
        print(f"ERROR: {results_path} does not exist. Run scripts/evaluate.py first.")
        # We don't want to sys.exit(1) if called from evaluate.py, 
        # but the plan said to do it for the standalone script.
        return

    with open(results_path, "r", encoding="utf-8") as f:
        results = json.load(f)

    agent_rows = results.get("agent", [])
    baseline_rows = results.get("baseline", [])
    metrics = ["faithfulness", "answer_relevancy", "context_precision", "context_recall"]

    if not agent_rows or not baseline_rows:
        print("ERROR: Results file is missing data sections.")
        return

    lines = []
    lines.append("# RAGAS Evaluation Report\n")
    lines.append(f"> Generated by `scripts/report.py` from `{results_path.name}`.\n")

    # --- Aggregate Summary Table ---
    lines.append("## Aggregate Scores\n")
    lines.append("| Metric | Baseline | Agent | Delta |")
    lines.append("|--------|----------|-------|-------|")
    for m in metrics:
        baseline_avg = sum(r[m] for r in baseline_rows) / max(len(baseline_rows), 1)
        agent_avg = sum(r[m] for r in agent_rows) / max(len(agent_rows), 1)
        delta = agent_avg - baseline_avg
        arrow = "▲" if delta > 0.001 else ("▼" if delta < -0.001 else "—")
        lines.append(f"| `{m}` | {baseline_avg:.4f} | {agent_avg:.4f} | {arrow} {abs(delta):.4f} |")
    lines.append("")

    # --- Per-Question Breakdown ---
    lines.append("## Per-Question Breakdown\n")
    # Zip might fail if lengths differ, but evaluate.py ensures they match
    for i, (a_row, b_row) in enumerate(zip(agent_rows, baseline_rows)):
        lines.append(f"### Q{i + 1}: {a_row['question']}\n")
        lines.append("| Metric | Baseline | Agent |")
        lines.append("|--------|----------|-------|")
        for m in metrics:
            b_score = b_row.get(m, float("nan"))
            a_score = a_row.get(m, float("nan"))
            lines.append(f"| `{m}` | {b_score:.4f} | {a_score:.4f} |")
        lines.append("")
        lines.append(f"**Baseline answer:**\n> {b_row['answer']}\n")
        lines.append(f"**Agent answer:**\n> {a_row['answer']}\n")
        lines.append("---")

    report_content = "\n".join(lines)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)
    print(f"Report written to {report_path}")

if __name__ == "__main__":
    generate_report()
